run.py: Convert server port to int
Otherwise, starting the server might fail with:

Traceback (most recent call last):
  File "run.py", line 47, in <module>
    server.start()
[...]
TypeError: an integer is required

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>